---
- name: "Installation de Logstash et dépendance JDK"
  yum: name="{{item}}" state=latest
  with_items:
    - "{{ java_package }}"
    - "logstash"

- name: "On garde le fichier jvm.ptions par défaut pour nos futures instances"
  copy:
    src: /etc/logstash/jvm.options
    dest: /tmp/jvm.options
    remote_src: yes

- name: "On supprime tous le contenu du /etc/logstash"
  file:
    path: /etc/logstash
    state: absent

- name: "Copie des fichiers de services des différentes instances logstash"
  copy:
    src: defaults/{{ item }}.service
    dest: /usr/lib/systemd/system/{{ item }}.service
  with_items:
    - "logstash-collect"
    - "logstash-analyse"
    - "logstash-class"

- name: "Rechargement des daemons"
  systemd: daemon_reload=yes
  
- import_tasks: logstash-instance.yml
